AT_04.23.10 | Verify "Notes/Remark" label is present and visible
RedRoverSchool/BookingProject pull request #320
Opened 2023-02-13 00:36 UTC by Forostinko

https://trello.com/c/JftbuQGZ/755-at042310-verify-notes-remark-label-is-present-and-visible

2023-02-13 03:38 UTC, Rom-T approved these changes

2023-02-13 03:38 UTC, Rom-T commented on cypress/pageObjects/CreateBookingPage.js
> +    getPlaceholderBookingNotes = () => cy.get('textarea#booking_notes')
Please change the name of the element to getNotesInputField

2023-02-13 03:46 UTC, SvetlanaKanel requested changes
You need to verify the label but you are verifying the placeholder

2023-02-13 03:52 UTC, Rom-T requested changes
Yes, I missed. The test is on the inputField, but on the label.

2023-02-13 16:54 UTC, Rom-T approved these changes

2023-02-14 19:19 UTC, Forostinko commented
>" You need to verify the label but you are verifying the placeholder @SvetlanaKanel  fixed

2023-02-14 19:50 UTC, Forostinko commented
> You need to verify the label but you are verifying the placeholder
@SvetlanaKanel fised

2023-02-18 13:36 UTC, Rom-T approved these changes

2023-02-19 20:45 UTC, SvetlanaKanel approved these changes

2023-02-20 20:49 UTC, closed without merging