AT_04.23.12 | Verify "Notes/Remark" label is present and visible
RedRoverSchool/BookingProject pull request #391
Opened 2023-02-21 19:25 UTC by Forostinko

https://trello.com/c/iSusEofv/816-at042312-verify-notes-remark-label-is-present-and-visible

2023-02-21 20:22 UTC, elviraKh1 commented on cypress/pageObjects/CreateBookingPage.js
> +    getNotesRemarkLabel = () => cy.get('.notes-row:nth-child(3) > label:nth-child(1)');
you could use a shorter selector, just  ".notes-row > label"

2023-02-21 20:28 UTC, elviraKh1 approved these changes

2023-02-21 20:28 UTC, Rom-T commented on cypress/e2e/testUiAndFunction/createBookingPage/US_04.23_PassengersDetailsDefaultUI.cy.js
> +            // .and('include.text', this.createBookingPage.dropdowns.fareType.labelName);
comments should be removed

2023-02-21 20:29 UTC, elviraKh1 approved these changes

2023-02-21 20:29 UTC, elviraKh1 requested changes

2023-02-21 20:29 UTC, elviraKh1 commented on cypress/e2e/testUiAndFunction/createBookingPage/US_04.23_PassengersDetailsDefaultUI.cy.js
> +    it.only('AT_04.23.13 | Verify Fare type has “Adult” option displayed by default.', function ()  {
it only shoul be removed

2023-02-21 20:32 UTC, Rom-T commented on cypress/e2e/testUiAndFunction/createBookingPage/US_04.23_PassengersDetailsDefaultUI.cy.js
> +    it.only('AT_04.23.13 | Verify Fare type has “Adult” option displayed by default.', function ()  {
Please delete only

2023-02-21 20:35 UTC, Rom-T commented on cypress/pageObjects/CreateBookingPage.js
> +    getFareTypeDrop = () => cy.get('#select2-passenger-fare-ur-container');
the same locator on line 60

2023-02-21 20:49 UTC, elviraKh1 submitted a review, later dismissed

2023-02-21 21:15 UTC, elviraKh1 commented on cypress/e2e/testUiAndFunction/createBookingPage/US_04.23_PassengersDetailsDefaultUI.cy.js
> +    i('AT_04.23.12 | Verify "Notes/Remark" label is present and visible.', function ()  {
i -> it

2023-02-22 03:27 UTC, Rom-T approved these changes

2023-02-22 11:39 UTC, EkaterinaRomankova approved these changes

2023-02-22 16:41 UTC, merged