AT_04.24.04 | Verify Notes/Remark input field has a “Booking notes” text placeholder and is visible
RedRoverSchool/BookingProject pull request #396
Opened 2023-02-22 18:43 UTC by Forostinko

https://trello.com/c/Q4VPdC4u/872-at042404-verify-notes-remark-input-field-has-a-booking-notes-text-placeholder

2023-02-22 19:11 UTC, Rom-T approved these changes

2023-02-22 19:12 UTC, Rom-T requested changes
Where is the visible check?

2023-02-22 20:32 UTC, elviraKh1 commented on cypress/e2e/testUiAndFunction/createBookingPage/US_04.24_Multiple_passengers_UI.cy.js
> +            .should('have.attr', 'placeholder', this.createBookingPage.placeholder.notes);
better use "and" instead of second "should"

2023-02-23 17:24 UTC, Rom-T approved these changes

2023-02-24 16:50 UTC, merged