RF | US _04.30 > check if clean method works after reservation
RedRoverSchool/BookingProject pull request #466
Opened 2023-03-02 15:14 UTC by OLgaByR

2023-03-02 16:07 UTC, MariaMoroz requested changes

2023-03-02 16:07 UTC, MariaMoroz commented on cypress/e2e/testUiAndFunction/createBookingPage/US_04.30_SummaryUI.cy.js
>  		});
Для чего двойное очищение? И потом, плохая практика очищать в конце теста. Так совсем не делают. Можно создать хук afterEach() на худой конец)) но ! в нашем случае это только трата лишнего времени, которое мы так стараемся сократить)))

2023-03-02 16:31 UTC, OLgaByR commented on cypress/e2e/testUiAndFunction/createBookingPage/US_04.30_SummaryUI.cy.js
>  		});
it is only in tests for reservation  , not double. hook after did not work locally for me

2023-03-03 13:12 UTC, Rom-T approved these changes

2023-03-03 19:21 UTC, MariaMoroz approved these changes

2023-03-04 16:46 UTC, closed without merging